server {
  listen 80 default_server;
  server_name _;
  return 404;
}

server {
  listen 80;
  server_name hello1.local hello1.example.test;
  root /srv/sites/hello1/current;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }
}

server {
  listen 80;
  server_name hello2.local hello2.example.test;
  root /srv/sites/hello2/current;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }
}

server {
  listen 80;
  server_name hello3.local hello3.example.test;
  root /srv/sites/hello3/current;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }
}
